import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "0.5rem",
        md: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        sm: "16px",
        base: "4px",
        gutter: "24px",
        lg: "40px",
        xs: "8px",
        xl: "64px",
      },
      fontFamily: {
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      colors: {
        background: "#0b1326",
        foreground: "#dae2fd",
        "primary-container": "#a078ff",
        "primary-fixed": "#e9ddff",
        "secondary-fixed": "#acedff",
        secondary: "#4cd7f6",
        "on-secondary-container": "#00424e",
        "inverse-on-surface": "#283044",
        "on-primary-fixed": "#23005c",
        "inverse-primary": "#6d3bd7",
        "tertiary-container": "#ff516a",
        "on-surface": "#dae2fd",
        "error-container": "#93000a",
        "surface-bright": "#31394d",
        "surface-container-highest": "#2d3449",
        "surface-container": "#171f33",
        "on-primary-container": "#340080",
        "surface-tint": "#d0bcff",
        "on-tertiary": "#67001b",
        "tertiary-fixed": "#ffdadb",
        error: "#ffb4ab",
        "secondary-container": "#03b5d3",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-surface-variant": "#cbc3d7",
        "surface-container-low": "#131b2e",
        "surface-dim": "#0b1326",
        surface: "#0b1326",
        "inverse-surface": "#dae2fd",
        "on-primary": "#3c0091",
        "on-secondary": "#003640",
        "surface-container-lowest": "#060e20",
        "on-tertiary-container": "#5b0017",
        tertiary: "#ffb2b7",
        outline: "#958ea0",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        primary: "#d0bcff",
        "surface-container-high": "#222a3d",
        "surface-variant": "#2d3449",
        border: "rgba(255, 255, 255, 0.1)",
        input: "rgba(255, 255, 255, 0.1)",
        ring: "#d0bcff",
        card: {
          DEFAULT: "#171f33",
          foreground: "#dae2fd",
        },
        popover: {
          DEFAULT: "#171f33",
          foreground: "#dae2fd",
        },
        muted: {
          DEFAULT: "#2d3449",
          foreground: "#cbc3d7",
        },
        accent: {
          DEFAULT: "#222a3d",
          foreground: "#dae2fd",
        },
        destructive: {
          DEFAULT: "#ffb4ab",
          foreground: "#690005",
        },
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        shimmer: "shimmer 2s infinite linear",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
